### ISSUE TITLE
Support for Cordova Cloud Build Environments

### ISSUE THREAD

**Issue by aesculus** [dpa99c/cordova-plugin-cloud-settings#1]
I had to ask.  For me PGB and Ionic are required.  Perhaps someone cleaver can come up with a way to do this with this plugin.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-plugin-cloud-settings#remote-build-environments) Phonegap Build and other "cloud build" environments are not supported because they don't support hook scripts.

Ionic Native provides Typescript wrappers around existing JS plugin interfaces. There's an [open PR](https://github.com/ionic-team/ionic-native/pull/2494) to merge a Typescript wrapper I created or you can use the JS plugin API directly from Ionic.

**Comment by aesculus** [comment]
Thanks for the comment. I was hoping someone might see the comment and come up with an alternative solution for the "hook scripts". Out of my league.
