### ISSUE TITLE
Maximum File Size

### ISSUE THREAD

**Issue by aesculus** [dpa99c/cordova-plugin-cloud-settings#2]
Any idea what the maximum file size that can be supported is?  I have both about 10kb of settings but also about 40 MB of data that I would love to be backed up to the devices cloud storage.

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-plugin-cloud-settings#ios) the limit on iOS is 1Mb per user per app. This is because native K/V store is used to save the settings.

On Android, a JSON file is used, so the limit is that of the Android Backup service - 25Mb per app.

If you want to store a larger file in the cloud on iOS, you can store it in the synced data area - see [cordova-plugin-file](https://github.com/apache/cordova-plugin-file#ios-file-system-layout) for details.
On Android, you'd need to override the autobackup rules generated by this plugin in order to include your additional larger file in the backup.

**Comment by aesculus** [comment]
Sorry. Missed that comment on the 1MB.

Thanks for the tip on the file plugin.
