### ISSUE TITLE
iOS: Works in local builds, fails when uploaded to TestFlight: getting error "synchronize failed"

### ISSUE THREAD

**Issue by pliablepixels** [dpa99c/cordova-plugin-cloud-settings#9]
Environment:
iPhone X
IOS 11.4.1

Hi, this plugin works great during development - I created a build and uploaded it to test flight for testing (before releasing it to the app store). The cloud plugin seems to fail with:

`"CloudSettingsPlugin ERROR saving settings: synchronize failed` 

The invoking code is:
```
 window.cordova.plugin.cloudsettings.save({
          'serverGroupList': ct,
          'defaultServerName': $scope.loginData.serverName
        },
        function () {
          NVRDataModel.debug("local data synced with cloud...");
        
        },
        function (err) {
          NVRDataModel.debug("error syncing cloud data..."+JSON.stringify(err));
         
        }, true);
```

If it matters, I have also enabled debug  like so:
```
window.cordova.plugin.cloudsettings.enableDebug(function(){
            console.log("Debug mode enabled");
        });
```

I re-installed my local build and it started working right away.

Entitlements:
<img width="1001" alt="screen shot 2018-09-15 at 1 38 37 pm" src="https://user-images.githubusercontent.com/4116654/45589039-bc8dc380-b8ec-11e8-966d-ddbe9e614b73.png">

Member Center for App ID:
 
<img width="699" alt="screen shot 2018-09-16 at 9 18 13 am" src="https://user-images.githubusercontent.com/4116654/45596908-9f5f0080-b991-11e8-8f91-47dfe2917e0f.png">

**Comment by pliablepixels** [comment]
@dpa99c do you see any issues in what I am doing? I've confirmed with other users who are using my TestFlight build that it fails for them too. Odd part is it works without any issues in local xcode->device builds

**Comment by dpa99c** [comment]
I'm using this plugin in production (iOS & Android) and not seeing these issues.
The difference is maybe in the iCloud settings - I have created a container and am enabling CloudKit Support (though not actually enabling it in Xcode):

![member_centre_icloud_container](https://user-images.githubusercontent.com/2345062/45822417-55ed1900-bce3-11e8-9d92-503402bc9be4.jpg)
![member_centre_app_id](https://user-images.githubusercontent.com/2345062/45822418-55ed1900-bce3-11e8-947d-637e41ff9524.jpg)
![xcode](https://user-images.githubusercontent.com/2345062/45822419-55ed1900-bce3-11e8-9c0f-1269408270e6.png)

**Comment by pliablepixels** [comment]
ok, I actually am currently doing what you are doing and I'm still facing this issue. But let me re-do it and confirm.

**Comment by pliablepixels** [comment]
Yup, reconfirmed, Here are my latest test flight build settings .Seems to be identical to yours.

My Xcode version: 10 (had the same issue with 9.x)

The app id for which I enabled iCloud settings:

![screen shot 2018-09-20 at 10 14 35 am](https://user-images.githubusercontent.com/4116654/45824585-52936680-bcbe-11e8-806f-04f644d8604d.png)

The settings in apple member portal:

![screen shot 2018-09-20 at 10 14 42 am](https://user-images.githubusercontent.com/4116654/45824621-6c34ae00-bcbe-11e8-8e41-ce6e563155dd.png)


My iCloud container (defined, not used)
![screen shot 2018-09-20 at 10 21 07 am](https://user-images.githubusercontent.com/4116654/45825029-465bd900-bcbf-11e8-959c-7c4b6897a527.png)



My Xcode Capability settings for the same project:

![screen shot 2018-09-20 at 10 15 46 am](https://user-images.githubusercontent.com/4116654/45824644-7d7dba80-bcbe-11e8-929f-cb00ad4beaf9.png)

And my provisioning profiles also have iCloud in them:

![screen shot 2018-09-20 at 10 19 36 am](https://user-images.githubusercontent.com/4116654/45824802-c6ce0a00-bcbe-11e8-9e65-4a0c203ee946.png)

**Comment by dpa99c** [comment]
When I have some time I'll have a look for some iOS device log output from my production app for comparison

**Comment by pliablepixels** [comment]
Here is a console app log from my test build version. This does not happen with the local build
Note that in my config.xml I have `  <preference name="BackupWebStorage" value="none" />`

![screen shot 2018-09-20 at 3 17 30 pm](https://user-images.githubusercontent.com/4116654/45841646-6ce23a00-bce8-11e8-8c46-631c629cd742.png)

**Comment by pliablepixels** [comment]
One last data point for today:
It looks like the iCloud entitlements are only added in the Debug build and not the Release build - is this something that the plugin is responsible for or am I messing up somewhere?

```
cat platforms/ios/zmNinja/Entitlements-Debug.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>aps-environment</key>
        <string>development</string>
        <key>com.apple.developer.icloud-container-identifiers</key>
        <array/>
        <key>com.apple.developer.ubiquity-kvstore-identifier</key>
        <string>$(TeamIdentifierPrefix)$(CFBundleIdentifier)</string>
</dict>
</plist>


 cat platforms/ios/zmNinja/Entitlements-Release.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>aps-environment</key>
    <string>production</string>
  </dict>

```

**Comment by dpa99c** [comment]
I've had a quick look into this and I think you are right that the problem is related to entitlements, and I believe it is indeed a bug with this plugin.

As I mentioned, I'm not encountering this issue in the production app in which I'm using this plugin. 
However, I now believe that to be due to pure chance that I'm using another plugin in that app which is silently fixing the issue with this plugin:

This plugin is uses a [hook script](https://github.com/dpa99c/cordova-plugin-cloud-settings/blob/master/hooks/ios/install_entitlements.js) to create an `.entitlements` file and link it to the Xcode project file (`project.pbxproj`) during [plugin/platform installation](https://github.com/dpa99c/cordova-plugin-cloud-settings/blob/master/plugin.xml#L69). 

When I just tested this plugin alone in isolation, I found that although the entitlements file is being created, it's not being linked to the Xcode project file. 
Therefore, if I open the project in Xcode and expand the `Resources` folder, I don't see the entitlements file.

But in my production app, I can see the entitlements file is present in the `Resources` folder in Xcode and has therefore been linked. If I edit the `project.pbxproj` in a text editor, I can see the entitlements file is indeed linked.
However, I don't believe this plugin is responsible for the successful linking, but by chance I'm also including [cordova-universal-links-plugin](https://github.com/nordnet/cordova-universal-links-plugin).
That plugin also includes [a hook script](https://github.com/nordnet/cordova-universal-links-plugin/blob/master/hooks/lib/ios/projectEntitlements.js) to include an entitlements file of the same name.
As a consequence, in my production project, it's the universal links plugin that has successfully linked the entitlements file, not this plugin.

Therefore, I need to fix this plugin so it correctly adds the entitlements. Looking at [this SO answer](https://stackoverflow.com/a/46372345/777265) it may be possible to do that by directly from the `plugin.xml` (without need of a hook script) by injecting the config into `Entitlements-Debug.plist` and `Entitlements-Release.plist` which are configs created by Cordova and linked up during the build process.

**Comment by pliablepixels** [comment]
Excellent. Thanks for the note. I think going the `Entitlements-Debug/Release.plist` route is good. Before you posted this note, I manually added the same cloud entitlement in the Debug file to the Release file:

```
<key>com.apple.developer.icloud-container-identifiers</key>
    <array/>
    <key>com.apple.developer.ubiquity-kvstore-identifier</key>
    <string>$(TeamIdentifierPrefix)$(CFBundleIdentifier)</string>
```

That got rid of this error, but I haven't yet been able to sync/recover data in an ad-hoc build ( which I am using for testing) - it doesn't report an error, but maybe this is a matter of sync time.I eagerly await your fix so I can test it - given my limited knowledge, I'm not entirely sure I am doing it correctly manually.

**Comment by dpa99c** [comment]
I've published your PR in v1.0.4 to npm - I'll re-test it on iOS when I get some time

**Comment by pliablepixels** [comment]
Thanks. I left my phone charged for 12 hrs and on wifi. The sync did not happen. The local file was created and I can see it on load but deleting the app and reinstalling it did not recover. As usual debug builds sync instantly. I'll try for more than 24 hrs now. (Edit: Forcing an iCloud backup did not work either, so I'm not sure production builds are  working)

**Comment by pliablepixels** [comment]
I can confirm that forcing backing via "backup now" finally worked for me in a production build. The modified plugin 1.0.4 works just fine.

Incase someone else faces an issue (or I forget and 3 months down the line and  google again), one of these  two things worked (this after trolling every possible post related to this topic on the Internet):

Summary:
**Your iCloud sync works wonderfully in development but not on deployment.**

1. You don't _need_ to enable "CloudKit" in the capabilities, but if you do enable it and you see an error next to "Add iCloud containers to your app ID" and you know you already have done that, just go to your bundle ID, add a random character, go back to capabilities and you'll find that problem is resolved. Now go back to App ID, change back and confirm the capabilities are also ok  and disable CloudKit. Truth be told, this did not directly resolve my issue - it took away that error but did not seem to backup data on a production build. But who knows. Listing it anyway. ([Credit](https://forum.unity.com/threads/problem-with-add-icloud-containers-to-you-app-id.500397/))

2. Before you turn a [flamethrower](https://www.boringcompany.com/not-a-flamethrower/) on your MacBook, log out of iCloud in your phone and log back on (Note that this will remove your credit cards in your pay wallet so you'll have to add it back, and may even need a phone reboot if it takes for ever to log back into iCloud)

Then re-install the production build, delete it, add it back, and the data is restored. _Et voilà_
